version: '3.8'
services:
    currency-analyst:
      container_name: app
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - SERVER_HOST=0.0.0.0
        - SERVER_PORT=3333
        - REDIS_HOST=redis_db
      volumes:
        - .:/currency-analyst
      working_dir: /currency-analyst
      ports:
        - "3333:3333"
      depends_on:
        - redis

    redis:
      image: redis:latest
      container_name: redis_db
      ports:
        - "6379:6379"
      command: ["redis-server", "--appendonly", "yes"]

    redis-commander:
      image: rediscommander/redis-commander:latest
      container_name: redis_ui
      environment:
        - REDIS_HOSTS=local:redis:6379
        - HTTP_USER=admin
        - HTTP_PASSWORD=admin
      ports:
        - "8081:8081"
      depends_on:
        - redis
