version: '3.8'
services:
    app:
      container_name: app
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        - SERVER_HOST=0.0.0.0
        - SERVER_PORT=3333
        - REDIS_HOST=redis_db
      volumes:
        - .:/currency-analyst
      working_dir: /currency-analyst
      ports:
        - "3333:3333"
      depends_on:
        - redis

    redis:
      image: redis:latest
      container_name: redis_db
      ports:
        - "6379:6379"
      command: ["redis-server", "--appendonly", "yes"]

    redis-commander:
      image: rediscommander/redis-commander:latest
      container_name: redis_ui
      environment:
        - REDIS_HOSTS=local:redis:6379
        - HTTP_USER=admin
        - HTTP_PASSWORD=admin
      ports:
        - "8081:8081"
      depends_on:
        - redis

    celery-worker:
      container_name: worker
      build: .
      command: celery -A celery_worker.celery worker --loglevel=info
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      depends_on:
        - app
        - redis

    celery-beat:
      container_name: cron
      build: .
      command: celery -A celery_worker.celery beat --loglevel=info
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      depends_on:
        - app
        - redis
        - celery-worker

    flower:
      container_name: flower_ui
      build: .
      command: celery -A celery_worker.celery flower --port=5555
      ports:
        - "5556:5555"
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
        - CELERY_RESULT_BACKEND=redis://redis:6379/0
      depends_on:
        - app
        - redis
        - celery-worker