version: '3.8'
services:
    currency-analyst:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/currency-analyst
      working_dir: /currency-analyst
      ports:
        - "8000:8000"
