version: '3.8'
services:
    currency-analyst:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/app
      working_dir: /app
      ports:
        - "8000:5000"